# Site settings
title: ModernTLD News, Articles, etc.
description: > # this means to ignore newlines until "baseurl:"
    ModernTLD provides free domain registration on the OpenNIC network.
    Keep up to date on this website to learn more about our operations
    and new developments!
url: "https://blog.moderntld.com/"
baseurl: ""
logo: "<b>ModernTLD</b> News"
paginate: 5
paginate_path: "/page:num/"
owner:
    email: jonah@moderntld.com
    facebook:
        show: false
        name: "ModernTLD"
        url: "https://fb.me/doesnotexist"
    github:
        show: true
        username: "ModernTLD"
    twitter:
        show: true
        username: "ModernTLD"
    disqus:
        show: true
        username: "jonaharagon"
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
markdown: redcarpet
highlighter: pygments
gems:
    - jekyll-feed
    - jekyll-paginate
